### ISSUE TITLE
Add "Load More" Functionality To Fund Search Results

### ISSUE THREAD

**Issue by alexfinnarn** [CUCentralAdvancement/giving-frontend#51]
https://github.com/bvaughn/react-window

That project has a few different ways to load the data in a list and a way to accomplish infinite scroll. I'm not too big a fan of infinite scroll since sometimes it is hard to get to the footer, if there is one, and on this site there is a footer.

**Comment by mattroush** [comment]
Gitlab issue: https://gitlab.com/cu-advancement/cu-giving/-/issues/390

**Comment by alexfinnarn** [comment]
This was actually made very easy with the Algolia Instantsearch library. It is set to 20 results by default and then loads 20 more. The number of items can be configured with a lot of other options as well.
