### ISSUE TITLE
Add integration point for posting to backend

### ISSUE THREAD

**Issue by alexfinnarn** [CUCentralAdvancement/giving-frontend#557]
The `userReducer` makes it easier to capture events and pipe them somewhere. The original post to create an order happened on loading `/checkout/complete`, but now that should move to the reducer. Removing Recoil and using an event bus made the code cleaner so it makes sense to delegate backend calls to the reducer vs. separating them out.

AC:
- [ ] Add posts to the gateway in `/data/contexts/UserContext.js` and refactor switch statement
- [ ] Look at how to make calls to backend and gateway once page loads to update stale data since the page was statically generated.

## Next Issue

There needs to be a way to check the state on page load. Initializing the user context is one touchpoint, but each route transition should also load something.

**Comment by imkleats** [comment]
@alexfinnarn - I've pushed a [develop/gateway-integration](/CUCentralAdvancement/giving-frontend/tree/develop/gateway-integration) branch that has some of (maybe all of...?) the refactoring I mentioned this morning & configuration to run some debug Donor Actions just to make sure the communication is happening appropriately until I get the full Gift Basket flow plugged in. Feel free to take a look if you're so inclined.

**Comment by alexfinnarn** [comment]
@imkleats Alright looks good so far. Can you keep going with this issue to completion? 

I guess completion would mean going through a traditional order from fund page to completion and sending data to the gateway, at least locally. I'm not sure with the private space what's needed to communicate, but I've been connecting giving-frontend to giving-backend on Heroku vs. running both locally for testing.

You can rewrite the Acceptance Criteria, but I would add one or more Cypress tests and then also a doc somewhere in `/docs` that explains the context, reducer, exposed public functions, and connection to the gateway in the style of onboarding a new developer to the project. 

I've never done it, but you can mock API responses using an `.intercept()` command: https://docs.cypress.io/guides/guides/network-requests#Testing-Strategies
