### ISSUE TITLE
`appeal_code` query parameter

### ISSUE THREAD

**Issue by mattroush** [CUCentralAdvancement/giving-frontend#571]
`appeal_code` is one of [the custom query parameters](https://github.com/CUCentralAdvancement/giving-frontend/blob/main/docs/custom-query-params.md) users can leverage and allows staff to link gifts in source system to a specific appeal or campaign for tracking/reporting purposes.

It should be accepted globally and can be added to any giving.cu.edu path and in combo with others as part of a query string. Site initially captures and stores client-side with the session, then retrieves and popluates corresponding field on Donation record object when user takes action to generate a new donation.

**Use Case:** Annual Giving wants to use an Advancement Intelligence (Cognos) report to track total donors and dollars for each of their annual campaigns.

**Validation:** Accepts any string (on user to ensure it is correct)
✅ : `giving.cu.edu?appeal_code=G1234`
❌ :  `colorado.edu?appeal_code=G1234`

### Acceptance Criteria
- [ ] if param is present in URI on any page at any point in a user's session, the site captures and stores it for duration of the user's session on the site.
- [ ] if param is present when a user visits a campaign page and the campaign has a default appeal code applied (*dev task TBD*), the default appeal code should be overriden with the parameter value provided.
- [ ] if a user with stored `appeal_code` initiates creation of a Donation in the same session, appeal code is retrieved and added to that Donation record
- [ ] appeal code is included with donation record in the gifts report/export

### Next Issue

Ensure Gateway schema and record creation/update support it.

**Comment by alexfinnarn** [comment]
@mattroush @imkleats It appears this query parameter will affect the session in giving-gateway so I will leave this one for thoughts. I'm not sure if this is the first piece of data that would need to be saved on website entry totally outside of the order workflow we've mostly talked about. The query param could be erased/lost so it needs to be saved on page load, I think.

**Comment by alexfinnarn** [comment]
taking off pinned so Stalebot can do its business.
