### ISSUE TITLE
`recurring` query parameter

### ISSUE THREAD

**Issue by mattroush** [CUCentralAdvancement/giving-frontend#572]
`recurring` is one of [the custom query parameters](https://github.com/CUCentralAdvancement/giving-frontend/blob/main/docs/custom-query-params.md) users can leverage, especially for campaigns that promote recurring giving.

On fund pages only, the site enables the "Make this a recurring gift" option in Add To Basket form and sets the recurring schedule based on param's value.

**Use Case:** UCCS wants to promote monthly recurring gifts as part of a campaign.

**Validation:** Value must be "monthly", "quarterly" or "annually" (not case sensitive)
✅ : `recurring=monthly`
❌ :  `recurring=daily`

### Acceptance Criteria

While the page is a fund page and param is present in URI...

- [x] site enables "Make this a recurring gift" option in Add to Basket form
  - https://giving-frontend.herokuapp.com/fund/cancer-research-general-fund?recurring=monthly
- [x] site sets recurring schedule field to the value corresponding to the param's value
  - https://giving-frontend.herokuapp.com/fund/cancer-research-general-fund?recurring=quarterly
- [ ] if param value is not valid, recurring schedule remains the default null value and user sees message saying "Please select a recurring gift schedule."
  - https://giving-frontend.herokuapp.com/fund/cancer-research-general-fund?recurring=mondays

### Next Issue

Deploy and test.

**Comment by alexfinnarn** [comment]
@mattroush https://giving-frontend.herokuapp.com/fund/cancer-research-general-fund?recurring=MonThLy still works because the characters are down-cased before the comparison is made. I think Next.js' router does this by default. Should it still fail to set the value then?

Linking to #440 where two checklist items were taken care of.

**Comment by mattroush** [comment]
@alexfinnarn - let it down-case and I'll change the A/C. I was describing current state, but nextjs default there is best.

**Comment by alexfinnarn** [comment]
taking off pinned so Stalebot can do its business.
